name: trade_stat
description: Trade Stat.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter


  intl: ^0.17.0
  cupertino_icons: ^1.0.2
  flutter_svg: ^1.1.6
  sqflite: ^2.2.2
  path_provider:
  flutter_bloc: ^8.1.1
  equatable: ^2.0.5
  hydrated_bloc: ^8.1.0
  image_picker: ^0.8.6
  plugin_platform_interface: ^2.1.0
  carousel_slider: ^4.2.1
  flutter_staggered_grid_view: ^0.6.2
  shared_preferences: ^2.0.15
  syncfusion_flutter_charts: ^20.4.44
  easy_localization: ^3.0.1
  google_mobile_ads: ^2.3.0
  permission_handler: ^9.2.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_launcher_icons: "0.12.0"


flutter:

  uses-material-design: true

  assets:
    - assets/images/profile.jpg
    - assets/images/app_logo.jpg
    - assets/images/instagram_image.jpg
    - assets/images/globe_web_image.jpg
    - assets/images/desc_image.svg
    - assets/images/welcome_screen_image.svg
    - assets/images/bottom_background.svg
    - assets/images/top_background_image.svg
    - assets/images/add_edit_deal_background.svg
    - assets/images/add_photo.svg
    - assets/images/no_data_image.svg
    - assets/icons/next_single_arrow.svg
    - assets/icons/burger_menu.svg
    - assets/icons/more_menu_icon.svg
    - assets/icons/add_deal_icon.svg
    - assets/icons/add_rule_icon_white.svg
    - assets/icons/rules_icon.svg
    - assets/icons/strategy_icon.svg
    - assets/icons/back_blue_icon.svg
    - assets/icons/edit_blue_icon.svg
    - assets/icons/tradestat_icon.png
    - assets/translations/


  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/montserrat_regular.ttf
          weight: 400
        - asset: fonts/montserrat_thin.ttf
          weight: 100
        - asset: fonts/montserrat_light.ttf
          weight: 200
        - asset: fonts/montserrat_medium.ttf
          weight: 500
        - asset: fonts/montserrat_semibold.ttf
          weight: 600
        - asset: fonts/montserrat_bold.ttf
          weight: 700
        - asset: fonts/montserrat_black.ttf
          weight: 700
        - asset: fonts/montserrat_italic.ttf
          weight: 400
          style: italic
    - family: Lato
      fonts:
        - asset: fonts/lato_regular.ttf
          weight: 400
        - asset: fonts/lato_thin.ttf
          weight: 100
        - asset: fonts/lato_light.ttf
          weight: 200
        - asset: fonts/lato_bold.ttf
          weight: 700
        - asset: fonts/lato_black.ttf
          weight: 700
        - asset: fonts/lato_italic.ttf
          weight: 400
          style: italic
